import Head from 'next/head';
import { gql } from '@apollo/client';

import Layout from '@/components/Layout/Layout';

import client from '@/utilities/ApolloClientConnection/ApolloClientConnection';

interface IPROPS {
  data: {};
}

const Home: React.FC<IPROPS> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <h2>helooo</h2>
        </main>
      </Layout>
    </>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      {
        user(login: "tausifabid12") {
          pinnedItems {
            totalCount
          }
          repositories {
            totalCount
          }
          watching {
            totalCount
            totalDiskUsage
          }
        }
      }
    `,
  });

  console.log(data);

  return {
    props: { data: data.user },
  };
}

export default Home;
