import Head from 'next/head';
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  createHttpLink,
  gql,
} from '@apollo/client';

import Layout from '@/components/Layout/Layout';
import InfoCard from '@/components/InfoCard/InfoCard';
import client from '@/utilities/ApolloClientConnection/ApolloClientConnection';
import TopInfoSection from '@/components/TopInfoSection/TopInfoSection';

interface IPROPS {
  data: {
    pinnedItems: {};
    repositories: {};
    watching: {};
  };
}

const Home: React.FC<IPROPS> = ({ data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <TopInfoSection data={data} />
        </main>
      </Layout>
    </>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      {
        user(login: "tausifabid12") {
          pinnedItems {
            totalCount
          }
          repositories {
            totalCount
            totalDiskUsage
          }
          watching {
            totalCount
          }
        }
      }
    `,
  });

  const { user } = data;
  console.log(user);
  return {
    props: { data: user }, // will be passed to the page component as props
  };
}

export default Home;
