import Head from 'next/head';
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  createHttpLink,
  gql,
} from '@apollo/client';

import Layout from '@/components/Layout/Layout';
import InfoCard from '@/components/InfoCard/InfoCard';
import client from '@/utilities/ApolloClientConnection/ApolloClientConnection';

interface IPROPS {
  pinnedItems: [];
}

const Home: React.FC<IPROPS> = ({ pinnedItems }) => {
  console.log(pinnedItems);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <div className="grid grid-cols-4 gap-5 px-5 py-10">
            <InfoCard />
            <InfoCard />
            <InfoCard />
          </div>
        </main>
      </Layout>
    </>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      {
        user(login: "tausifabid12") {
          pinnedItems(first: 6) {
            totalCount
            edges {
              node {
                ... on Repository {
                  id
                  name
                  url
                }
              }
            }
          }
        }
      }
    `,
  });

  const { user } = data;
  const pinnedItems = user?.pinnedItems?.edges.map(
    (node: { __typename: string; id: string; name: string; url: string }) =>
      node
  );

  return {
    props: { pinnedItems }, // will be passed to the page component as props
  };
}

export default Home;
